# Global configurations
listen              1935;
max_connections     1000;
daemon              off;

# HTTP server configurations
http_server {
    enabled         on;
    listen          1985;
    dir             ./objs/nginx/html;
}

# WebRTC server configurations
rtc_server {
    enabled         on;
    listen          8000; 
    # candidate     ${CANDIDATE};
}

vhost __defaultVhost__ {
    rtc {
        enabled             on;
        # WHIP/WHEP configurations
        whip {
            enabled         on;
        }
        whep {
            enabled        on;
        }
        # Video codec configurations
        preferred_codec    H264;  # Prioritize VP8 for transparency support
        all_codecs        on;   # Support all codecs for better quality
        bframe            0;     # Disable B-frames for lower latency
        rgba              on;    # Enable transparency support
        scaling           off;   # Disable automatic scaling to prevent blur
        abr {
            enabled       off;   # Disable adaptive bitrate
        }
    }

    http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
    }

    play {
        gop_cache       on;
        queue_length    10;
        mw_latency     100;
    }

    publish {
        transcode       off;    # Disable transcoding to preserve quality
        mr {
            enabled     off;    # Disable media reactor
        }
    }
}
